os: linux
dist: focal
arch: amd64
virt: lxd
group: dev

jobs:
  include:
     - language: perl
       perl: 
       - 5.33.0
       script:
         - perl helloworld.pl
         
     - language: perl
       perl: 
       - 5.32.0
       script:
         - perl helloworld.pl
         
     - language: erlang
       script:
       - erl -noshell -eval 'io:fwrite("Hello, World!\n"), init:stop().'
    
     - language: python
       python: 
       - 3.7
       script: 
       - python python_hw.py
    
     - language: python
       python: 
       - 3.8
       script: 
       - python python_hw.py
    
     - language: python
       python:
       - nightly
       script: 
       - python python_hw.py
    
     - services: 
       - elasticsearch
       script:
       - systemctl status elasticsearch
       - sleep 10
       - curl 127.0.0.1:9200
      
     - services: 
       - couchdb
       script:
       - sleep 10
       - systemctl status couchdb
       - netstat -nltp
      
     - services: 
       - mongodb
       script:
       - sleep 10
       - systemctl status mongodb
       - netstat -nltp

     - services: 
       - postgresql
       script:
       - travis_setup_postgresql 12
       - sleep 10
       - systemctl status postgresql@12-main
       - netstat -nltp
       
     - services: 
       - mysql
       script:
       - sleep 11
       - systemctl status mysql
       
     - services: 
       - mariadb
       script:
       - sleep 11
       - systemctl status mariadb
