os: linux
dist: focal
arch: amd64
virt: lxd
group: dev

jobs:
  include:
    - language: erlang
     script:
     - erl -noshell -eval 'io:fwrite("Hello, World!\n"), init:stop().'
    
   - language: python
     python: 
     - 3.7
     script: 
     - python python_hw.py
    
   - language: python
     python: 
     - 3.8
     script: 
     - python python_hw.py
    
   - language: python
     python:
     - nightly
     script: 
     - python python_hw.py
